
package ihe.iti.rfd._2007;

import javax.jws.WebService;
import javax.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "FormProcessor_Port_Soap12", serviceName = "FormProcessor_Service", targetNamespace = "urn:ihe:iti:rfd:2007", wsdlLocation = "file:/home/rmoult01/eclipseProjects/rfd/git/erl-ihe-rfd/erl-ihe-rfd/src/wsdl/RFDFormProcessor.wsdl", endpointInterface = "ihe.iti.rfd._2007.FormProcessorPortType")
@BindingType("http://www.w3.org/2003/05/soap/bindings/HTTP/")
public class FormProcessor_Service_FormProcessor_Port_Soap12Impl
    implements FormProcessorPortType
{


    public FormProcessor_Service_FormProcessor_Port_Soap12Impl() {
    }

    /**
     * Corresponds to Transaction ITI-34 of the IHE Technical Framework
     * 
     * @param body
     * @return
     *     returns ihe.iti.rfd._2007.RetrieveFormResponseType
     */
    public RetrieveFormResponseType formProcessorRetrieveForm(RetrieveFormRequestType body) {
        //replace with your impl here
        return null;
    }

    /**
     * Corresponds to Transaction ITI-XXX of the IHE Technical Framework
     * 
     * @param body
     * @return
     *     returns ihe.iti.rfd._2007.RetrieveFormResponseType
     */
    public RetrieveFormResponseType formProcessorRetrieveClarification(RetrieveClarificationRequestType body) {
        //replace with your impl here
        return null;
    }

    /**
     * Corresponds to Transaction ITI-35 of the IHE Technical Framework
     * 
     * @param body
     * @return
     *     returns ihe.iti.rfd._2007.SubmitFormResponseType
     */
    public SubmitFormResponseType submitForm(AnyXMLContentType body) {
        //replace with your impl here
        return null;
    }

}
